project:
  title: "Lab 3: Covid-19"
  subtitle: "Ecosystem Science and Sustainability 330"""
  author: 
    - name: Ainsley Denham
      email: denhamam@colostate.edu
  output-dir: docs
  type: website
  
format:
  html:
    self-contained: true